<<<<<<< HEAD
theme: jekyll-theme-slate
logo: [https://imgur.com/a/2Uxn8bP]
title: [whatever]
description: [donate.zona.media]
=======
theme: jekyll-theme-minimal
>>>>>>> d3af7a5bdb565e554033a377ed72d1b2b027236e
